FROM node:20-alpine

COPY . .
RUN yarn install

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_USE_SDK
ARG NEXT_PUBLIC_HOSTNAME

RUN echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> .env
RUN echo "NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}" >> .env
RUN echo "NEXT_PUBLIC_USE_SDK=${NEXT_PUBLIC_USE_SDK}" >> .env
RUN echo "NEXT_PUBLIC_HOSTNAME=${NEXT_PUBLIC_HOSTNAME}" >> .env
RUN yarn build
EXPOSE 3003
CMD ["yarn", "run", "start"]
